blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://discord.gg/rx35NzQGSb
    about: The issue tracker is exclusively for reporting bugs and suggesting new features. For support, please visit our Discord!